### ISSUE TITLE
Make URLs dynamic on the hardhat config

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/solidity-template#12]
Instead of `KOVAN_URL` we should do something like `https://${netwokr}.infura.io/v3/SECRET`

**Comment by rellfy** [comment]
I think this would only work on some providers, like infura. Alchemy seems to have one network per key.

**Comment by rellfy** [comment]
I think we should close this. I don't see the benefit in hardcoding most of the URL to a specific provider like infura.
