### ISSUE TITLE
Refactor to make more typescript like

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/solidity-template#23]

**Comment by rellfy** [comment]
Can you provide some examples on this?

**Comment by Theresa77a** [comment]
Do you wanna earn even just at home, or are you interested in making huge income each week, I'll like to use this medium to introduce to you bitcoin trade.Trade binary & forex trade with the help of a professional trader Elizabeth Towles.She reliable and trusted.Simply contact her through the link below to get started👇👇
WhatsApp: +1(689)225-9867
